version: '3'

volumes:
  postgres_data: {}
  templates: {}
  media: {}

services:

  database:
    image: postgres:alpine
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - ./docker/backend/.env

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        HTTP_PROXY: '' #http://127.0.0.1:3128
    restart: unless-stopped
    volumes:
      - 'templates:/app/templates'
      - 'media:/app/media'
    ports:
      - 8000:80

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        HTTP_PROXY: '' #http://127.0.0.1:3128
    restart: unless-stopped
    command: sh run.sh
    env_file:
      - ./docker/backend/.env
    volumes:
      - 'templates:/app/assets/templates'
      - 'media:/app/assets/media'
    expose:
      - 8000