version: '3'

volumes:
  postgres_data: {}
  media: {}

services:

  database:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - docker/.env

  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    command: /run.sh
    entrypoint: /entrypoint.sh
    env_file:
      - docker/.env
    ports:
      - 8000:8000
    volumes:
      - 'media:/app/assets/media'